<?php require_once __DIR__.'/config/config.php'; ?>
<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>INTERLANDIA SaaS</title>
<script src="https://cdn.tailwindcss.com"></script><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.3/jspdf.plugin.autotable.min.js"></script>
<style>body{background:#070b18;color:#e5e7eb}.card{background:#10172a;border:1px solid #24304d;border-radius:18px}.inp{background:#08111f;border:1px solid #2d3b5f;border-radius:10px;padding:10px;width:100%}.btn{border-radius:10px;padding:10px 14px;font-weight:700}.qtdc{display:flex;flex-direction:column;align-items:center;line-height:1.05}.cmark{font-size:11px;color:#facc15;font-weight:900}.sidebar a{display:block;padding:11px;border-radius:12px}.sidebar a:hover{background:#17213a}</style></head><body>
<div id="login" class="min-h-screen grid place-items-center p-4"><div class="card w-full max-w-md p-8"><img src="assets/logo_dragao.jpg" class="w-28 h-28 object-contain mx-auto mb-4"><h1 class="text-2xl font-black text-center text-yellow-400">INTERLANDIA LTDA</h1><p class="text-center text-slate-400 mb-6">Sistema SaaS Profissional</p><input id="user" class="inp mb-3" value="admin" placeholder="Usuário"><input id="pass" class="inp mb-4" type="password" value="admin123" placeholder="Senha"><button onclick="login()" class="btn bg-yellow-500 text-slate-950 w-full">Entrar</button><p id="erro" class="text-red-400 mt-3"></p><p class="text-xs text-slate-400 mt-4">admin/admin123 • conferente/admin123 • motorista/admin123</p></div></div>
<div id="app" class="hidden min-h-screen md:flex"><aside class="sidebar w-full md:w-72 bg-slate-950 border-r border-slate-800 p-4"><img src="assets/logo_dragao.jpg" class="w-20 h-20 object-contain"><h2 class="font-black text-yellow-400 mt-2">INTERLANDIA</h2><p id="perfil" class="text-sm text-slate-400 mb-4"></p><a onclick="show('dashboard')">📊 Dashboard</a><a onclick="show('cargas')">🚚 Cargas</a><a onclick="show('cadastros')">🧾 Cadastros/Admin</a><a onclick="show('importar')">📥 Importar Excel</a><a onclick="emitirPDF()">📄 Emitir PDF</a><a onclick="logout()">🚪 Sair</a></aside><main class="flex-1 p-4 md:p-7 overflow-auto">
<section id="dashboard"><h1 class="text-3xl font-black mb-4">Painel Administrativo</h1><div id="cards" class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4"></div><div class="card p-4 mb-4"><h3 class="font-bold mb-2">Paletes por cliente</h3><div id="clientesHorizontal" class="flex gap-3 overflow-x-auto pb-2"></div></div><div class="grid md:grid-cols-2 gap-4"><div class="card p-4"><canvas id="chartStatus"></canvas></div><div class="card p-4"><canvas id="chartCliente"></canvas></div></div></section>
<section id="cargas" class="hidden"><div class="flex flex-wrap gap-2 justify-between mb-4"><h1 class="text-3xl font-black">Controle de Cargas</h1><button onclick="abrirNova()" class="btn bg-yellow-500 text-slate-950">+ Nova carga</button></div><input id="busca" oninput="renderCargas()" class="inp mb-4" placeholder="Buscar NF, SAP, cliente ou motorista"><div class="card overflow-auto"><table class="w-full text-sm"><thead class="text-yellow-400"><tr><th class="p-3">NF</th><th>SAP</th><th>Cliente</th><th>Motorista</th><th>Placa</th><th>Qtde</th><th>Status</th><th>Ações</th></tr></thead><tbody id="tbody"></tbody></table></div></section>
<section id="cadastros" class="hidden"><h1 class="text-3xl font-black mb-4">Cadastros</h1><div class="grid md:grid-cols-2 gap-4"><div class="card p-4"><h3 class="font-bold mb-3">Novo usuário</h3><input id="unome" class="inp mb-2" placeholder="Nome"><input id="uuser" class="inp mb-2" placeholder="Usuário"><input id="upass" class="inp mb-2" value="123456" placeholder="Senha"><select id="urole" class="inp mb-2"><option value="conferente">Conferente</option><option value="motorista">Motorista</option><option value="master">Master</option></select><button onclick="salvarUsuario()" class="btn bg-blue-600">Salvar usuário</button></div><div class="card p-4"><h3 class="font-bold mb-3">Cliente</h3><input id="crazao" class="inp mb-2" placeholder="Razão social"><input id="ccnpj" class="inp mb-2" placeholder="CNPJ"><input id="cuf" class="inp mb-2" maxlength="2" placeholder="UF"><button onclick="salvarCliente()" class="btn bg-blue-600">Salvar cliente</button></div></div></section>
<section id="importar" class="hidden"><h1 class="text-3xl font-black mb-4">Importação Excel/CSV</h1><div class="card p-4"><input type="file" id="arquivo" accept=".xlsx,.xls,.csv" class="inp mb-3"><button onclick="importarExcel()" class="btn bg-green-600">Importar</button><p class="text-sm text-slate-400 mt-3">Colunas recomendadas: nota_fiscal, sap, cliente_nome, cnpj, uf, motorista, placa, transportadora_nome, qtde, valor_unitario, marcar_c</p></div></section>
</main></div>
<div id="modal" class="hidden fixed inset-0 bg-black/70 grid place-items-center p-4"><div class="card p-5 w-full max-w-3xl"><div class="flex justify-between"><h2 class="text-xl font-black">Nova carga</h2><button onclick="modal.classList.add('hidden')">✕</button></div><div class="grid md:grid-cols-3 gap-3 mt-4"><input id="nf" class="inp" placeholder="Nota Fiscal"><input id="sap" class="inp" placeholder="SAP"><input id="cliente" class="inp" placeholder="Cliente"><input id="cnpj" class="inp" placeholder="CNPJ"><input id="uf" class="inp" placeholder="UF"><input id="motorista" oninput="validarMotoristaAberto()" class="inp" placeholder="Motorista"><input id="placa" class="inp" placeholder="Placa"><input id="transportadora" oninput="autoC()" class="inp" placeholder="Transportadora"><input id="representante" class="inp" placeholder="Representante"><input id="qtde" class="inp" type="number" placeholder="Qtde"><input id="valor" class="inp" type="number" value="100" placeholder="Valor unitário"><label class="flex items-center gap-2"><input id="marcarC" type="checkbox"> colocar C embaixo da Qtde</label></div><p id="alerta" class="hidden bg-red-950 border border-red-700 p-3 rounded-xl mt-3 text-red-200"></p><button id="btnSalvar" onclick="salvarCarga()" class="btn bg-yellow-500 text-slate-950 mt-4">Salvar carga</button></div></div>
<script>
let token='', me=null, cargas=[], dashboard=null, ch1=null, ch2=null; const API='api/index.php?action=';
async function req(action,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{}); if(token) opt.headers.Authorization='Bearer '+token; const r=await fetch(API+action,opt); const j=await r.json(); if(!r.ok) throw new Error(j.erro||'Erro'); return j;}
async function login(){try{const j=await req('login',{method:'POST',body:JSON.stringify({username:user.value,password:pass.value})}); token=j.token; me=j.user; localStorage.jwt=token; loginDiv(false); await load();}catch(e){erro.innerText=e.message}}
function loginDiv(v){document.getElementById('login').classList.toggle('hidden',!v);document.getElementById('app').classList.toggle('hidden',v);document.getElementById('app').classList.toggle('md:flex',!v);perfil.innerText=me?`${me.nome} • ${me.role}`:''}
function logout(){localStorage.removeItem('jwt');location.reload()} function show(id){['dashboard','cargas','cadastros','importar'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id)); if(id==='cargas') renderCargas();}
async function load(){const d=await req('dashboard'); dashboard=d; const c=await req('cargas'); cargas=c.cargas; renderDash(); renderCargas();}
function renderDash(){let total=cargas.length,pal=cargas.reduce((s,c)=>s+Number(c.qtde),0),ab=cargas.filter(c=>c.status==='ABERTO').length,vale=cargas.filter(c=>c.status==='VALE PALLETE').length; cards.innerHTML=[['Total cargas',total],['Paletes',pal],['Abertas',ab],['Vale pallete',vale]].map(x=>`<div class='card p-5'><div class='text-slate-400'>${x[0]}</div><div class='text-3xl font-black text-yellow-400'>${x[1]}</div></div>`).join(''); clientesHorizontal.innerHTML=dashboard.clientes.map(c=>`<div class='min-w-56 card p-4'><b>${c.cliente_nome||'Sem cliente'}</b><div class='text-2xl text-yellow-400 font-black'>${c.paletes}</div><small>${c.cargas} cargas</small></div>`).join(''); const s=dashboard.status; if(ch1)ch1.destroy(); ch1=new Chart(chartStatus,{type:'doughnut',data:{labels:s.map(x=>x.status),datasets:[{data:s.map(x=>x.qtd)}]}}); if(ch2)ch2.destroy(); ch2=new Chart(chartCliente,{type:'bar',data:{labels:dashboard.clientes.map(x=>x.cliente_nome).slice(0,8),datasets:[{label:'Paletes',data:dashboard.clientes.map(x=>x.paletes).slice(0,8)}]}});}
function renderCargas(){let q=(busca?.value||'').toLowerCase(); let list=cargas.filter(c=>JSON.stringify(c).toLowerCase().includes(q)); tbody.innerHTML=list.map(c=>`<tr class='border-t border-slate-800'><td class='p-3'>${c.nota_fiscal}</td><td>${c.sap||''}</td><td>${c.cliente_nome||''}</td><td>${c.motorista||''}</td><td>${c.placa||''}</td><td><span class='qtdc'><b>${c.qtde}</b>${Number(c.marcar_c)?'<span class="cmark">C</span>':''}</span></td><td>${c.status}</td><td><button class='btn bg-green-700' onclick='retorno(${c.id},"CONCLUÍDO")'>Retorno</button> <button class='btn bg-purple-700' onclick='retorno(${c.id},"VALE PALLETE")'>Vale</button></td></tr>`).join('')||'<tr><td class=p-4 colspan=8>Nenhum registro</td></tr>';}
function abrirNova(){modal.classList.remove('hidden');alerta.classList.add('hidden');btnSalvar.disabled=false;['nf','sap','cliente','cnpj','uf','motorista','placa','transportadora','representante'].forEach(id=>document.getElementById(id).value='');qtde.value='';valor.value=100;marcarC.checked=false;}
function autoC(){ if(transportadora.value.toUpperCase().includes('INTERLANDIA')) marcarC.checked=true; }
function validarMotoristaAberto(){let m=motorista.value.trim().toLowerCase(); let existe=cargas.find(c=>(c.motorista||'').toLowerCase()===m && c.status==='ABERTO'); alerta.classList.toggle('hidden',!existe); alerta.innerText=existe?`Motorista já possui carga ABERTA: ${existe.nota_fiscal}`:''; btnSalvar.disabled=!!existe;}
async function salvarCarga(){try{await req('cargas',{method:'POST',body:JSON.stringify({nota_fiscal:nf.value,sap:sap.value,cliente_nome:cliente.value,cnpj:cnpj.value,uf:uf.value,motorista:motorista.value,placa:placa.value,transportadora_nome:transportadora.value,representante_nome:representante.value,qtde:qtde.value,valor_unitario:valor.value,marcar_c:marcarC.checked?1:0})});modal.classList.add('hidden');await load();}catch(e){alert(e.message)}}
async function retorno(id,status){let motivo=status==='VALE PALLETE'?prompt('Motivo do vale:')||'':''; await req('retorno',{method:'POST',body:JSON.stringify({id,status,motivo_vale:motivo})}); await load();}
async function salvarUsuario(){try{await req('usuarios',{method:'POST',body:JSON.stringify({nome:unome.value,username:uuser.value,password:upass.value,role:urole.value})});alert('Usuário salvo');}catch(e){alert(e.message)}}
async function salvarCliente(){try{await req('clientes',{method:'POST',body:JSON.stringify({razao:crazao.value,cnpj:ccnpj.value,uf:cuf.value})});alert('Cliente salvo');}catch(e){alert(e.message)}}
async function importarExcel(){const f=arquivo.files[0]; if(!f)return alert('Escolha um arquivo'); const data=await f.arrayBuffer(); const wb=XLSX.read(data); const linhas=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); const j=await req('importar',{method:'POST',body:JSON.stringify({linhas})}); alert(j.importados+' linhas importadas'); await load();}
function emitirPDF(){const {jsPDF}=window.jspdf; const doc=new jsPDF('l'); doc.text('Relatório de Cargas - INTERLANDIA',14,12); doc.autoTable({head:[['NF','SAP','Cliente','Motorista','Qtde','C','Status']],body:cargas.map(c=>[c.nota_fiscal,c.sap,c.cliente_nome,c.motorista,c.qtde,Number(c.marcar_c)?'C':'',c.status])}); doc.save('relatorio_interlandia.pdf');}
(async()=>{if(localStorage.jwt){token=localStorage.jwt; try{let j=await req('me'); me=j.user; loginDiv(false); await load();}catch(e){localStorage.removeItem('jwt')}}})();
</script></body></html>
